src/NodeInfoProvider.tsx
src/components/OpenWallet.tsx
src/pages/collators/Collators.tsx
src/pages/dashboard/Dashboard.tsx

Bugfix/ampe balance not visible (develop)

---

src/NodeInfoProvider.tsx
src/components/OpenWallet.tsx
src/pages/collators/Collators.tsx
src/pages/dashboard/Dashboard.tsx

fix https://github.com/pendulum-chain/portal/issues/25

Bugfix/ampe balance not visible (master)

---

src/pages/collators/Collators.tsx
src/pages/dashboard/styles.css

- Fixes double scroll issue
- Makes header sticky
Before
Still not a nice table but it's something

fix double scroll, make header sticky

---

.github/workflows/semantic-release.yml
package.json
release.config.cjs

I made a small mistake. The version command is reserved and the version increment action did not work.

chore: fix release

---

package.json
src/hooks/staking/staking.tsx
src/pages/collators/Collators.tsx
src/pages/collators/dialogs/ConfirmDelegateDialog.tsx
src/pages/collators/dialogs/DelegateToCollatorDialog.tsx
src/pages/collators/dialogs/DelegationSuccessfulDialog.tsx
src/pages/collators/dialogs/ExecuteDelegationDialogs.tsx
src/pages/collators/dialogs/helpers.ts
yarn.lock

Closes #27 
Some things to consider:
- I reused the same dialogs than for delegation, changing texts and actions. Maybe a bit dirty (a couple of extra booleans and checks), but that won against duplicating everything.
- For that reason I also had to reset the booleans everytime onClose(), because the dialogs are always in the dom, and the state only manages their visibility.

27 add undelegation functionality

---

index.html
src/components/Layout/index.tsx
src/components/Layout/styles.sass
src/components/OpenWallet.tsx
src/components/Skeleton/index.tsx
src/components/Table/GlobalFilter/index.tsx
src/components/Table/index.tsx
src/helpers/general.ts
src/hooks/staking/staking.tsx
src/index.css
src/pages/collators/Collators.tsx
src/pages/collators/columns.tsx
src/pages/dashboard/styles.css

feat: Collators table

---

src/app.tsx
src/pages/stats/index.tsx
src/services/stats/index.tsx

- Results are shown in `/<chain>/stats`
- I _had to_ include it inside the Portal since we already have a Router in place (it was the easiest)
- I added the mininum design to it
Closes #89

Add total issuance stats & others

---

src/components/Layout/ComingSoonTag.tsx
src/components/Layout/Nav.tsx
src/components/Layout/links.tsx
src/components/Layout/styles.sass
src/components/OpenWallet.tsx
src/index.css
tailwind.config.cjs

- Add coming soon tag
- Infere colors for Amplitude (designs missing)
- Side change: fixed OpenWallet colors to support both themes

73 update menu items with coming soon

---

src/components/Layout/index.tsx
src/components/Layout/styles.sass

add foucoco tag

---

src/components/Layout/links.tsx
src/components/Layout/styles.sass

126 minor fixes

---

package.json
src/helpers/spacewalk.ts
src/pages/bridge/TransferDialog.tsx
yarn.lock

123 show memo on the pending request

---

src/pages/dashboard/Dashboard.tsx

fix redirect

---

src/components/ChainSelector.tsx
src/helpers/string.ts
src/pages/bridge/Transfers.tsx
src/pages/bridge/TransfersColumns.tsx

- Show 'To <chain_name>' instead of 'To Pendulum' in Transfers Type col

Un-hardcode Type column

---

src/components/Selector/LabelledSelector.tsx
src/helpers/spacewalk.ts
src/pages/bridge/Issue.tsx

- Removed warning about issuer for XLM
-  Removed 'issued by' for XLM requests

Fix/136 Add support for XLM vaults

---

src/components/Layout/links.tsx
src/components/Layout/styles.sass
src/pages/dashboard/styles.css

minor fixes

---

src/pages/dashboard/Dashboard.tsx

Add orml token balances to Portfolio

---

src/pages/bridge/Issue.tsx
src/pages/bridge/Redeem.tsx
src/pages/bridge/TransfersColumns.tsx

- Updated confirmation dialog
- Changed Transaction ID to Request ID on the transfers table
- Closes #172

Fix redeem dialog

---

src/GlobalStateProvider.tsx
src/NodeInfoProvider.tsx
src/components/ChainSelector.tsx
src/hooks/useAccountBalance.ts
src/main.tsx
src/pages/dashboard/Dashboard.tsx

Try to solve the generic problem of multiple loading of the API and consequently of other components.
Also:
Closes #157

Stop loading loop

---

src/pages/bridge/index.tsx
src/pages/bridge/styles.css

129 amplitude dialogs text color change

---

src/components/Layout/styles.sass
src/index.css

https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/portal/80

fix: table heading overlap #80

---

src/assets/pendulum-icon-loading.svg

Makes it a bit more in line with the main website with the swing animation. Not perfect but close enough.

refactor: updated logo animation

---

src/components/LabelledInputField/index.tsx
src/components/Wallet/index.tsx
src/pages/bridge/Issue.tsx
src/pages/bridge/Redeem.tsx

174 dont initiate issue or redeem requests for invalid values

---

src/pages/collators/dialogs/ClaimRewardsDialog.tsx

fix amount formatting

---

src/components/Layout/links.tsx

- Adds an 'external link' icon to 'Buy PEN' sidebar link

add external link icon

---

src/pages/collators/dialogs/ClaimRewardsDialog.tsx

fix loading in claiming steps

---

src/hooks/spacewalk/useBridgeSettings.ts
src/pages/bridge/index.tsx
yarn.lock

fix: Show vaults for selected asset on Bridge Settings

---

src/pages/bridge/Issue/index.tsx

fix: Update disclaimer text for Spacewalk

---

.github/workflows/release.yml

Test whether semantic release works.

use GITHUB_TOKEN

---

src/components/Table/index.tsx
src/components/Table/styles.css
src/pages/bridge/Transfers.tsx
src/pages/bridge/TransfersColumns.tsx

feat: Make rows clickable in Spacewalk Transfers table

---

src/components/Layout/links.tsx

refactor: Remove Nabla menu link on Pendulum

---

src/pages/bridge/Redeem/ConfirmationDialog.tsx

fix: Fix Back to Stellar confirmation dialog

---

src/pages/collators/CollatorRewards.tsx
src/pages/collators/Collators.tsx
src/pages/collators/dialogs/ClaimRewardsDialog.tsx
src/pages/collators/dialogs/ValidationSchema.ts
src/pages/collators/styles.css

feat: Update designs for Updating and Claiming staking rewards

---

src/pages/collators/CollatorColumns.tsx

feat: Indicate if a collator reached its max delegators amount

---

src/helpers/spacewalk.ts
src/hooks/spacewalk/useBridgeSettings.ts

fix: Remove mainnet USDC asset from AssetSelector in Foucoco

---

src/helpers/spacewalk.ts

fix: Fix function for filtering assets

---

src/app.tsx
src/components/Layout/links.tsx

Enable Spacewalk for Pendulum
✅ Remove route guard in the navigation
✅ Enable Spacewalk for Pendulum in the Sidebar links

feat: Enable Spacewalk for Pendulum

---

.github/workflows/release.yml

The setup is following the steps described [here](https://gonzalohirsch.com/blog/semantic-release-and-branch-protection-rules/). 
Closes #375.

feat: Use Pendulum Bot for semantic releases

---

src/pages/bridge/Issue/ConfirmationDialog.tsx
src/pages/bridge/Issue/index.tsx

Redirect to spacewalk /transfers after issue request
✅ Add Bridge/Issue/Dialog onConfirm prop
✅ Add navigateTo on dialog onConfirm

chore: Redirect to spacewalk /transfers after issue request

---

src/pages/bridge/Issue/index.tsx
src/pages/bridge/Redeem/index.tsx
src/pages/bridge/helpers.ts

XLM top of the list in the Spacewalk asset dropdown
✅ Implement prioritizeXLMAsset function
✅ Use prioritizeXLMAsset for assets in "To Pendulum/Amplitude" and "Back To Stellar"

chore: implement prioritize XLM Asset

---

src/pages/bridge/index.tsx

Show Icon for Foucoco Spacewalk bridge
✅ Use TenantName for checking the network
✅ Add check for Foucoco network

chore: Show Icon for Foucoco Spacewalk bridge

---

src/pages/bridge/Issue/ConfirmationDialog.tsx
src/pages/bridge/TransferDialog.tsx

Update the note text on the spacewalk "to Pendulum" flow
✅ Update note text
✅ Add a link to Pendulum telegram

chore: Update the note text on the spacewalk "to Pendulum" flow

---

src/pages/collators/dialogs/ClaimRewardsDialog.tsx

Fix max amount claim rewards
add fullMax to <Amount /> in Claim Rewards

fix max amount claim rewards

---

src/helpers/calc.ts
src/pages/collators/CollatorColumns.tsx
src/pages/collators/CollatorsTable.tsx

Change APY to APR /staking
Closes: #357

Chore: Change APY to APR

---

src/hooks/useBalances.ts

Adds a quick-fix for showing correct amounts for the DOT token. 
Closes #383.

Fix DOT decimals

---

src/pages/bridge/Issue/index.tsx
src/pages/bridge/Redeem/index.tsx

Error: [big.js] Invalid number
Instead of passing a number to create Big, selectedVault was of type { amount: number } which was causing the error
✅  handle selectedVault of type number and { amount: number }

fix: handle selectedVault of type number and { amount: number }

---

src/pages/bridge/Issue/ConfirmationDialog.tsx
src/pages/bridge/Issue/index.tsx
src/pages/bridge/TransferDialog.tsx

Add warning for adding memo during transfer
✅ Add Text
Closes: #396

Add warning for adding memo during transfer

---

src/components/Layout/Nav.tsx
src/components/Layout/links.tsx

Reorder the side menu
1. Dashboard
2. Spacewalk
3. Forex AMM
4. Staking
5. Governance
✅ Reorder links
✅ Fix margin of collapse nav item

Reorder the side menu

---

src/components/Layout/Nav.tsx

fix font class of nav items

---

src/services/walletConnect/index.ts

Add metadata for walletconnect

---

src/components/Layout/links.tsx

Submitting this quick PR to add Zenlink redirect to Pendulum, Hope its ok.

Added Zenlink redirect to Pendulum

---

src/config/apps/nabla.ts

Point to Foucoco (Paseo) instance

---

src/pages/spacewalk/bridge/Redeem/index.tsx

Closes https://github.com/pendulum-chain/tasks/issues/432.

Fix max available balance in redeem view

---

src/components/nabla/Pools/Swap/columns.tsx

Fix apr not shown

---

src/components/nabla/Pools/Swap/columns.tsx

- changed APR to APR(7d)
- Removed + $PEN from columns

Updated APR text
