.github/workflows/semantic-release.yml

Because the branch is protected semantic release needs the token to allow it to commit to it. Hopefully this works as I am not able to test this beforehand.

chore: fix ci token for protected branch

---

src/components/Skeleton/index.tsx
src/hooks/useIdentityPallet.ts
src/pages/collators/Collators.tsx
src/pages/collators/columns.tsx

- Added usePalletIdentity hook
- Added a function to fetch the identity info of a single account address
- Pre fetch identities for all collators to show in the table
- **Note**: this slows down the loading of the table a bit, if we want to make it non-blocking, then the collators name column would remain empty for some time which is also bad UX.
-  Collator column shows (in the following order, if first is missing): display > email > twitter > account id

Fetch collator identities

---

src/helpers/spacewalk.ts

Fixes the issue with currencies not shown on Amplitude. The problem is that currently, on-chain there are assets with a code that have a space character, but the stellar-sdk won't create `Asset`s that contain a space character. 
Because the space character on-chain is problematic in the first place, we don't want/need to handle that edge case and instead don't show these assets.

Wrap currency conversion with try-catch

---

src/hooks/staking/staking.tsx
src/pages/collators/dialogs/DelegateToCollatorDialog.tsx
src/pages/collators/dialogs/ExecuteDelegationDialogs.tsx

- Added an error if input value is higher than available (will also work for bonding)
- Compared values as floating point numbers to check if undelegation amount and available amount are equal
Closes #146

146 unbond not working on pendulum and amplitude

---

src/pages/bridge/TransferDialog.tsx

Fixes [this](https://github.com/pendulum-chain/tasks/issues/65) issue.
I changed the namings in the dialog a bit to make it clearer which address/account ID belongs to which network (Stellar vs parachain).

Fix wrong parameter used for deriving a vault's Stellar address

---

src/GlobalStateProvider.tsx
src/constants/localStorage.ts
src/hooks/useLocalStorage.ts
src/services/storage/local.ts
src/services/storage/types.ts

Adds an expiry date option to items in local storage.
- It adds another item to local storage to save the expire date for that item
- I wasn't sure where to put it, so I placed it while rendering the `GlobalStateProvider`
- Not very secure since users can change expire date from storage, so we don't need to rely on this mechanism for anything else than simple usage

add expiry date to local storage hooks

---

src/components/Pools/Backstop/index.tsx

feat: updated backstop pool ui

---

src/NodeInfoProvider.tsx
src/assets/CopyIcon.tsx
src/assets/socials-telegram.tsx
src/components/LabelledSelector/index.tsx
src/components/Layout/Versions.tsx
src/components/NotFound.tsx
src/components/Selector/AssetSelector.tsx
src/components/Selector/LabelledSelector.tsx
src/components/Selector/VaultSelector.tsx
src/components/Tabs/index.tsx
src/components/TickerChangeTable/index.tsx
src/hooks/spacewalk/fee.tsx
src/hooks/spacewalk/issue.tsx
src/hooks/spacewalk/redeem.tsx
src/hooks/spacewalk/security.tsx
src/hooks/spacewalk/vaultRegistry.tsx
src/pages/bridge/TransfersColumns.tsx
src/pages/collators/dialogs/ConfirmDelegateDialog.tsx

I noticed that we may have different settings regarding organising imports. Sometimes we might have conflicts with this, or we miss an unused import. So I run the `organise imports` action for the whole project, and I encourage you to add to your VSCode settings (if you use it) or similar:
```
"editor.codeActionsOnSave": {
"source.organizeImports": true
}, 
```

organize imports in the project

---

src/components/Layout/NetworkId.tsx
src/components/Layout/Versions.tsx
src/index.css

Fix versions & runtime in navbar

---

src/pages/collators/CollatorRewards.tsx

fetch unstaking tokens

---

src/components/Selector/AssetSelector.tsx
src/pages/bridge/Issue.tsx
src/pages/bridge/Redeem.tsx
src/pages/bridge/index.tsx

- Changed on Issue fee box
- Changed on Redeem fee box and asset selector
- Now, both Amplitude and Pendulum show the same suffix `.s`
Closes #187

187 change name of spacewalk tokens on UI

---

.github/workflows/ci.yml
.github/workflows/release.yml

You can merge it asap. This should fix the release. I believe the token does not have some permissions needed so it fails to fetch with depth: 0. Hopefully it did not expire.

fix: release

---

src/components/Layout/Versions.tsx

Removing the green indicators since they were a bit confusing and not part of the designs.

Remove alpha/foucoco indicator

---

src/hooks/spacewalk/useBridgeSettings.ts
src/pages/dashboard/Portfolio.tsx

App wise, we import hooks and components for preact/compat. The use of the _auto import_ feature from VsCode sometimes made a few exceptions, importing from react. To be consistent in our code, I removed the exceptions in this PR.

fix: Import react components from preact/compat

---

src/components/Layout/Nav.tsx
src/components/Layout/index.tsx
src/components/Layout/links.tsx
src/components/Layout/styles.sass

Implement collapse styles for sidebar button with dropdown.
Remove Chevron from active sidebar button without dropdown.
Change semantics of sidebar to improve accessibility.
Closes #207

fix: Implement collapsible buttons for sidebar

---

src/pages/bridge/Issue/Disclaimer.tsx
src/pages/bridge/Issue/index.tsx

fix: Update disclaimer text for bridge 

---

src/pages/bridge/Redeem/index.tsx

Filling in the Redeem form tries to autofill with personal credentials. Expected behaviour is that the form does not autofill with this data.
Implement autoComplete="off" for the input.
Closes: #163

fix: Turn off autoComplete for Back to Stellar address input

---

src/helpers/stellar.ts

In the Spacewalk, experiencing the error:
Error converting currency to stellar asset ReferenceError: Buffer is not defined
Fixed by implementing `window.Buffer = Buffer;`
Closes: #345

fix: add Buffer polyfill to window global object

---

src/components/Form/Amount/index.tsx

When user decides to stakes with "MAX" button, the entire PEN balance is considered in that transaction leaving no tokens for the user to execute the transaction i.e no gas fees to execute the transaction
Add BALANCE_LEFT_FOR_TX_APPROVAL constant variable.
Closes: #296

fix: add balance left for tx approval: staking

---

.github/workflows/release.yml
release.config.cjs

Configure semantic-release to add release commit on feature branch when PR is closed
✅ Update Github Actions Workflow
✅ Update semantic-release config to include creation of Github Release
The failures were due to Semantic-Release attempting to push both the "release tag" and the "release commit" directly to a protected branch.

chore: Configure semantic-release to add release commit on feature branch when PR is closed

---

.github/workflows/ci.yml
.github/workflows/release.yml
release.config.cjs

Change Github Actions to point on the `main` as we removed the `staging`

chore: change workflows to point on the main branch

---

src/pages/collators/dialogs/unlock/UnlockDialog.tsx

Change: "Unlock staked tokens" to "Unlock unstaked tokens"
Closes: #423

fix typo unlock unstaked modal

---

src/components/Selector/VaultSelector.tsx

Which user interface was the bug observed on?
Portal Spacewalk Bridge settings wheel crashes the interaction
What steps did you take?
Portal
Bridge
Change Asset to EURC
Settings wheel
Check manually select vault
UI freezes nothing else possible to select click or get out of the menu
The vault object has nested `amount` property that stores the required value. We passed the object `{ amount: "number-value"}` instead of a valid numeric value to the Big constructor.
Closes: #445

Screen freezes when manually selecting vault for EURC on Spacewalk

---

src/pages/bridge/FeeBox.tsx
src/pages/bridge/Issue/index.tsx

Don't show security deposit for redeem requests.
Adds an extra prop to show/hide the security deposit.
Closes #438.

Add prop for showing security deposit

---

src/pages/bridge/Issue/index.tsx

Fixes an issue where the error message stays after changing the selected assets.
Triggers the validation on all form fields when the selected asset or the max issuable amount changes.
Closes #441.

Trigger form validation when selected asset changes

---

src/components/nabla/Swap/index.tsx
src/components/nabla/common/TokenApproval.tsx

When a user does a swap and clicks on the Approve button, the button disappers while loading
✅ Refactor Nabla submit button
Closes: #468

fix nabla swap submit button

---

src/components/Layout/NavCollapseButtonContent.tsx
src/components/Layout/links.tsx
src/components/Layout/spacewalkAnimation.ts

When you hover your cursor over “Stellar Bridge” in the navigation, the Lottie animation starts playing, however, if you click on it while the animation is playing, the animation stops and cannot continue.
✅ Add `isClickToPauseDisabled={true}` to the Lottie component
✅ Add `createLottieOptions` function to make the code less repetitive
⚠️ Note
In the console this Lottie error appears:
`Failed prop type: Invalid prop 'style' of type 'object' supplied to 'Lottie2', expected 'string'`
The error appears since the day we implemented it, unfortunately the developer of the react-lottie library implemented the types incorrectly and the styles of the `<Lottie>` component cannot be implemented without this error

fix lottie animation stops playing onclick

---

src/pages/spacewalk/bridge/Redeem/index.tsx

Triggers the validation for the redeem form immediately. Aligns the `disabled` prop for the 'Bridge' button to the issue form.
Closes #510.

Trigger validation in redeem immediately and improve `disabled` field

---

src/pages/spacewalk/bridge/Issue/index.tsx
src/pages/spacewalk/bridge/Redeem/ConfirmationDialog.tsx

Adds the missing slash to the URL when redirecting after creating a new Spacewalk request.
Closes #509.

Fix missing slash in redirect

---

src/components/Selector/VaultSelector.tsx
src/hooks/spacewalk/useBridgeSettings.ts
src/pages/spacewalk/bridge/Issue/SettingsDialog.tsx
src/pages/spacewalk/bridge/index.tsx

The problem that 'broke' the feature in the first place is that the RPC call for `getVaultsWithIssuableTokens()` for some reason returns an empty array on Pendulum at the moment.
Closes #508.

Fix parsing of amounts in vault selector

---

src/config/apps/nabla.ts

Point to Nabla instance for testnet campaign

---

src/components/Selector/AssetSelector/helpers.ts
src/components/Selector/AssetSelector/index.tsx
src/components/Selector/DropdownSelector.tsx
src/shared/AssetIcons.tsx

✅ Unify AssetItem object (now it uses AssetItem interface, it already has name - so all of the AssetItem helper functions are private, and all the needed properties are already in the object)
✅ Change the structure of AssetIcons to avoid repetition

improve code readability

---

src/pages/spacewalk/bridge/Issue/index.tsx
src/pages/spacewalk/bridge/helpers.ts

Adds a new function to filter hidden assets and uses it for the assets shown in the issuing dialogs. 
Closes #522.

Hide Mykobo EURC when issuing to Pendulum and Amplitude

---

src/pages/spacewalk/bridge/Issue/Disclaimer.tsx
src/pages/spacewalk/bridge/Issue/index.tsx

Updates the disclaimer texts shown in the issue dialog. 
Closes #458 and closes #459.

Update disclaimer texts for Amplitude and Pendulum

---

netlify/functions/alchemypay.mts
package.json
src/components/Layout/Nav.tsx
src/components/Layout/links.tsx
src/config/index.ts
src/services/alchemypay/index.ts
yarn.lock

Closes #536 and closes https://github.com/pendulum-chain/tasks/issues/382

Fix redirect to AlchemyPay

---

src/hooks/spacewalk/useBridgeSettings.ts
src/hooks/spacewalk/useVaultRegistryPallet.ts
src/pages/spacewalk/bridge/Issue/SettingsDialog.tsx
src/pages/spacewalk/bridge/index.tsx

The problem was that some of the info that needed to be shared between the settings dialog and the issue/redeem form was stored locally in each call to `useBridgeSettings`. Moving the relevant items out of the state of the hook and into the context fixes this issue. 
Closes #553.

Fix manual vault selection not changing vault

---

src/components/CloseButton.tsx
src/components/PublicKey/ClickablePublicKey/index.tsx
src/components/PublicKey/CopyablePublicKey/index.tsx
src/components/PublicKey/index.tsx
src/components/Wallet/modals/DisconnectModal/index.tsx
src/pages/spacewalk/bridge/Issue/ConfirmationDialog.tsx
src/pages/spacewalk/bridge/Issue/SettingsDialog.tsx
src/pages/spacewalk/bridge/Redeem/ConfirmationDialog.tsx
src/pages/spacewalk/bridge/TransferDialog/TransferDialog.tsx
src/pages/spacewalk/transactions/TransactionDialog.tsx
src/pages/spacewalk/transactions/TransferDialog/CancelledTransferDialog.tsx
src/pages/spacewalk/transactions/TransferDialog/CompletedTransferDialog.tsx
src/pages/spacewalk/transactions/TransferDialog/PendingTransferDialog.tsx
src/pages/spacewalk/transactions/TransferDialog/TransferDialog.tsx
src/pages/staking/CollatorColumns.tsx

🦈 
---
As a user, I want view the complete address of the issuer in the popup window when creating an issue request, so that I can easily identify who issued the asset.
At the moment, the issuer's address is not fully visible, or copyable.
Requirements
Changes:

Make the issuer's address copyable similar to vault address and memo (Spacewalk)

---

src/components/Selector/VaultSelector.tsx
src/hooks/spacewalk/useBridgeSettings.ts
src/hooks/spacewalk/useVaultRegistryPallet.ts
src/pages/spacewalk/bridge/Issue/index.tsx
src/pages/spacewalk/bridge/Redeem/index.tsx
src/pages/spacewalk/bridge/index.tsx

Changes the automatic vault selection to select the vault with the most issuable tokens (when bridging to Pendulum) or the vault with the most redeemable tokens (when bridging to Stellar) by default. 
Refactors the code a bit to simplify the usage of the `issuableTokens` and `redeemableTokens` on the `ExtendedVault` types. 
Closes #556.

Improve manual vault selection for spacewalk amplitude and pendulum

---

src/components/Wallet/modals/DisconnectModal/index.tsx
src/helpers/substrate.ts
src/shared/useAccountBalance.ts

Makes the button in the top-right hand corner always show the transferable balance instead of the total balance.
Closes #485.

Show the portal pen balance only for transferrable tokens

---

src/hooks/useWalletConnection/useConnectWallet/index.tsx

I simplified the code by removing unnecessary state management, as the wallets are only filtered once and don’t require reactivity

remove unnecessary useEffect in useConnectWallet

---

src/components/Wallet/modals/DisconnectModal/index.tsx
src/helpers/substrate.ts

🦈 PR 🟢
---
After recent changes, we encountered an issue where accounts with a zero balance resulted in a negative transferable balance, specifically -0.00 (See image in the #609).
For accounts with a free balance of 0, `calculateTransferableBalance` can produce a negative value (specifically -0.001) because the EXISTENTIAL_DEPOSIT is set to 0.001, causing a deduction even when the free balance is zero.

dont calculate TransferableBalance when balance is 0

---

src/shared/constants.ts

Closes #620.
Note that the deploy preview will not show the prices either as the cors setting only allows portal.pendulumchain.org to query from the endpoint. To confirm that the query works you can use curl and query it locally though.
Works
```
$ curl -X POST https://eu-api.pendulumchain.tech/currencies -H "Content-Type: application/json" -d '[{"blockchain": "FIAT", "symbol": "BRL-USD"}]'
[{"symbol":"BRL-USD","name":"BRL-USD","blockchain":"FIAT","supply":0,"lastUpdateTimestamp":1731676265,"price":172491116707}]%                                                                                                                        
```
Doesn't work
```
$ curl -X POST https://batching-server.pendulumchain.tech/currencies -H "Content-Type: application/json" -d '[{"blockchain": "FIAT", …
```

Change batching server endpoint

---

src/components/nabla/Pools/Swap/columns.tsx

Add PEN to APR
This is for the liquidity campaign participants that they would receive PEN tokens as rewards along with the APR

Added +PEN to APR

---

netlify/functions/alchemypay.mts
src/pages/fund-wallet/FundWalletTabsContent/helpers.tsx

AlchemyPay changed the naming of the `crypto` parameter for the PEN token. We need to change it to make our redirect work again.

Fix alchemypay redirect not prefilling PEN

---

package.json
src/shared/showToast.ts
yarn.lock

A bug was detected that would crash the application when `CopyablePublicKey` was used (and clicked). Root cause was an undetermined bug in `react-toastify`, when `toast` was called.
Simply updating the dependency solved the issue.

Fix crash when address is copied to clipboard.

---

src/components/Wallet/modals/DisconnectModal/index.tsx
src/pages/spacewalk/bridge/Issue/index.tsx
src/shared/useAccountBalance.ts

The problem occurs only for accounts with a large balance of PEN tokens. The `useAccountBalance` hook returned the values with _pretty formatting_. This means that large amounts were depicted with commas, e.g. `10,000.00`.  The consumer of this balance could wrongly interpret the number as 10 PEN (if the comma is expected to denote the decimals) which is exactly what happened when transforming the transferable balance for calculating the security deposit. 
This PR changes the return type of `useAccountBalance` to return numbers instead. 
Closes #631.

Fix buggy calculation of transferable amount for security deposit

---

src/components/Table/index.tsx
src/components/nabla/common/OldForexAmmNotice.tsx
src/config/apps/nabla.ts
src/pages/nabla/backstop-pools/index.tsx
src/pages/nabla/swap-pools/index.tsx
src/pages/nabla/swap/index.tsx

- Create a component for the link to the old instance
- Show it on top of each swap page
I set up a separate deployment for the `old-forex-amm` branch in Netlify. The old instance is now available at https://old-forex-amm--rococo-souffle-a625f5.netlify.app.

Point to other amm instance

---

src/GlobalStateProvider/index.tsx
src/NodeInfoProvider.tsx
src/pages/spacewalk/bridge/index.tsx
src/services/modal/index.tsx
src/shared/Provider.tsx

Simple lexical sugar change
In React 19, you can render <Context> as a provider instead of <Context.Provider>
https://react.dev/blog/2024/12/05/react-19#context-as-a-provider

[READY] remove unnecessary .Provider as React19 doesnt require it
